# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: FlutterGitUI.FlutterGitUI
PackageVersion: ${VERSION}
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: flutter_gitui.exe
    PortableCommandAlias: flutter-gitui
Installers:
  - Architecture: x64
    InstallerUrl: ${DOWNLOAD_URL}
    InstallerSha256: ${SHA256}
ManifestType: installer
ManifestVersion: 1.6.0
